/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fileutil

import (
	"os"
	"path/filepath"

	"github.com/coze-dev/coze-studio/backend/pkg/logs"
)

func GetPythonFilePath(fileName string) string {
	cwd, err := os.Getwd()
	if err != nil {
		logs.Warnf("[GetPythonFilePath] Failed to get current working directory: %v", err)
		return fileName
	}

	// Local dev layout generated by scripts/setup/python.sh:
	// - venv under <repo>/bin/.venv
	// - scripts copied to <repo>/bin/<fileName>
	//
	// But the backend server is often started with cwd=<repo>/backend, so we search upwards.
	dir := cwd
	for i := 0; i < 3; i++ {
		candidates := []string{
			filepath.Join(dir, fileName),
			filepath.Join(dir, "bin", fileName),
		}
		for _, p := range candidates {
			if _, err := os.Stat(p); err == nil {
				return p
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	// Fallback: keep original behavior; caller will surface a clearer error if missing.
	return filepath.Join(cwd, fileName)
}

func GetPython3Path() string {
	cwd, err := os.Getwd()
	if err != nil {
		logs.Warnf("[GetPython3Path] Failed to get current working directory: %v", err)
		return ".venv/bin/python3"
	}

	// Search upwards for either:
	// - <dir>/.venv/bin/python3 (common)
	// - <dir>/bin/.venv/bin/python3 (repo script)
	dir := cwd
	for i := 0; i < 3; i++ {
		candidates := []string{
			filepath.Join(dir, ".venv", "bin", "python3"),
			filepath.Join(dir, "bin", ".venv", "bin", "python3"),
		}
		for _, p := range candidates {
			if _, err := os.Stat(p); err == nil {
				return p
			}
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}

	return "python3" // use system python3
}
